= CalConnect Standard: Calendaring -- Task Extensions to iCalendar

This work item belongs to CalConnect TC TASKS.

image:https://github.com/CalConnect/cc-ical-tasks/workflows/generate/badge.svg["Build Status", link="https://github.com/CalConnect/cc-ical-tasks/actions?workflow=generate"]

This document is available in its rendered forms here:

* https://calconnect.github.io/cc-ical-tasks/[CalConnect: Calendaring and scheduling -- Vocabulary (HTML)]

== General

This document specifies the (TITLE).

The document is published as the following:

* CalConnect CC 11001
* ISO 11001
* IETF draft-cc-ical-tasks


== Fetching the document

[source,sh]
----
git clone https://github.com/CalConnect/cc-ical-tasks/
----


== Installing build tools

See https://www.metanorma.com/author/topics/install/


== Running via Docker or locally

If you have installed the build tools locally, and wish to run the
locally-installed compilation tools, there is nothing further to set.

If you don't want to deal with local dependencies, use the docker:

[source,sh]
----
docker run -v "$(pwd)":/metanorma -w /metanorma -it metanorma/mn metanorma site generate --agree-to-terms
----


== Building the document

[source,sh]
----
metanorma site generate --agree-to-terms
----

The generated documents are accessible under `_site/`.


== Iterating the document

[source,sh]
----
metanorma site generate --agree-to-terms
open _site/index.html
----


== IETF: Checking against idnits

https://tools.ietf.org/tools/idnits/[idnits] is the RFC checking tool prior to
submissions.

[source,sh]
----
idnits draft-calconnect-ical-tasks.nits
----


== License

Copyright its respective authors and CalConnect.
