
[#iana]
== IANA Considerations
=== Component Registrations

This document defines the following new iCalendar component to be
added to the Components registry
defined in <<RFC5545, section=8.3.1>> and located here: <https://www.iana.org/assignments/icalendar#components>.

.Addition to the Components Registry
[cols="a,a,a",options=header]
|===
| Component           | Status  | Reference

| VSTATUS | Current | This Spec, <<vstatus>>

|===

=== Property Registrations

This document defines the following new iCalendar properties to be
added to the Properties registry
defined in <<RFC5545, section=8.3.2>> and located here: <https://www.iana.org/assignments/icalendar>.

.Additions to the Properties Registry
[cols="a,a,a",options=header]
|===
| Property           | Status  | Reference

| ESTIMATED-DURATION | Current | This Spec, <<prop-estimated-duration>>
| REASON    | Current | This Spec, <<prop-reason>>
| SUBSTATE  | Current | This Spec, <<prop-substate>>
| STATUS             | Current | This Spec, <<prop-ext-status>>
| TASK-MODE          | Current | This Spec, <<prop-task-mode>>

|===

=== Initialization of the Status Value registry

This document requests creation of a new iCalendar registry called "STATUS Values" for values of the "STATUS" property defined in <<RFC5545, section=3.8.1.11>>.

Additional values MAY be used, provided the process of "Standards Action with Expert Review" as described in
Section 8.2.1 of [RFC5545] is used to register them, using the
template in Section 8.2.6 of [RFC5545].

The following table has been used to initialize the Status Value
Registry.

.Initial Status Value Registry
[cols="a,a,a",options=header]
|===
| Name          | Status | Reference

| CANCELLED    | Current | <<RFC5545, section=3.8.1.11>>
| COMPLETED    | Current | <<RFC5545, section=3.8.1.11>>
| CONFIRMED    | Current | <<RFC5545, section=3.8.1.11>>
| DRAFT        | Current | <<RFC5545, section=3.8.1.11>>
| FAILED    | Current | This Spec, <<prop-ext-status>>
| FINAL        | Current | <<RFC5545, section=3.8.1.11>>
| IN-PROCESS   | Current | <<RFC5545, section=3.8.1.11>>
| NEEDS-ACTION | Current | <<RFC5545, section=3.8.1.11>>
| PENDING   | Current | This Spec, <<prop-ext-status>>
| TENTATIVE    | Current | <<RFC5545, section=3.8.1.11>>

|===

=== Substate Value registry

This document requests creation of a new iCalendar registry called "SUBSTATE Values" for values of the "SUBSTATE" property defined in <<prop-substate>>.

Additional values MAY be used, provided the process of "Standards Action with Expert Review" described in
Section 8.2.1 of [RFC5545] is used to register them, using the
template in Section 8.2.6 of [RFC5545].

The following table has been used to initialize the Substate Value
Registry.

.Initial Substate Value registry
[cols="a,a,a",options=header]
|===
| Substate  | Status  | Reference

| OK        | Current | This Spec, <<prop-substate>>
| ERROR     | Current | This Spec, <<prop-substate>>
| SUSPENDED | Current | This Spec, <<prop-substate>>

|===

=== Task Mode Value registry

This document requests creation of a new iCalendar registry called "TASK-MODE Values" for values of the "TASK-MODE" property defined in <<prop-task-mode>>.

Additional values MAY be used, provided the process of "Standards Action with Expert Review" described in
Section 8.2.1 of [RFC5545] is used to register them, using the
template in Section 8.2.6 of [RFC5545].

The following table has been used to initialize the Task Mode Value
Registry.

.Task Mode Value Registry
[cols="a,a,a",options=header]
|===
| Task Mode            | Status  | Reference

| AUTOMATIC-COMPLETION | Current | This Spec, <<prop-task-mode>>
| AUTOMATIC-FAILURE    | Current | This Spec,  <<prop-task-mode>>
| AUTOMATIC            | Current | This Spec,  <<prop-task-mode>>
| CLIENT               | Current | This Spec,  <<prop-task-mode>>
| SERVER               | Current | This Spec,  <<prop-task-mode>>

|===

=== Participation Statuses registry

This document defines the following new iCalendar participation status
to be added to the registry defined in Section 8.3.7 of [RFC5545] and
located here: <https://www.iana.org/assignments/icalendar#participation-statuses>

.Participation Statuses Registry
[cols="a,a,a",options=header]
|===
| Value    | Status  | Reference

| FAILED    | Current | This Spec, <<param-val-partstat>>

|===

